### ISSUE TITLE
Render list of Sessions

### ISSUE THREAD

**Issue by brynwhyman** [kinglozzer/silverstripe-session-manager#12]
### Overview
With the scaffolding work complete in https://github.com/silverstripe/silverstripe-session-manager/issues/11, now the field needs to be filled with Session data.

### Acceptance Criteria
- [x]  Pass session list for given Member to SessionManagerField through schema
- [x]  Render sessions based on [designs](https://projects.invisionapp.com/share/ANZZEC4XUTQ#/screens/439163639_CMS_-_Login_-_Session_Management_-_Remove_A_Device_-_List)
- [x] Last active hours converts to ‘days’ after 24 hours
- [x] For the current session, display the current IP address (not currently in the designs)
- [x] The current browser is being rendered with the ‘Current’ label
- [x] Common user agent definitions (browsers/ devices) are tested and the label reviewed
- [x] Readme is updated along with the image of the UI
- [x] The old Sessions tab is removed
- [x] The "Log Out" links prompt a confirmation warning before removing the session
- [x] The ‘Devices’ label has been reviewed for usefulness
- [x] It's been reviewed if there's usefulness in including a timestamp related to the current session data.
- [x] The order of this component in the Member UI is verified with PUX

### Notes
- The MFA component has a fairly similar layout so you may see some hints for building this out there.
- Consider the future need of being able to add a geo-location in replacement of the IP address. Can this be built in an extensible way now?

### PR
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/25

**Comment by brynwhyman** [comment]
> It's been reviewed if there's usefulness in including a timestamp related to the current session data.

@clarkepaul, FYI the module is already storing the 'signed in' timestamp as well as the 'last accessed' timestamp. Maybe that would be useful here? See: [screenshot of current behaviour](https://github.com/silverstripe/silverstripe-session-manager/blob/1/images/cms.png)

**Comment by bergice** [comment]
Just noting that the "Signed in" information will not be visible with the new designs: 
![image](https://user-images.githubusercontent.com/541886/109731261-cb34d600-7c1f-11eb-9647-5ac307c1a112.png)

May be worth adding this again.

Thoughts @clarkepaul ?

----

It's also worth noting that these changes may cause more of a maintenance burden in the long run as we are essentially replicating what the existing grid field does, but as a one-off solution not used anywhere else.
Some people may also prefer having data in a separate tab, instead of appending it to the main area.
In addition to that, the `Learn More` link in the designs are not a part of our current API.

**Comment by clarkepaul** [comment]
All valid points. The designs were done to align with the managing of MFA methods and were done prior to me seeing a screenshot of this module (I thought it was needing to be a new UI). I haven't personally stepped through that experience e.g. what happens with revoking sessions and notifications but I think its worth another conversation around whether its worth creating a new UI when this might be sufficient as an MVP.

**Comment by brynwhyman** [comment]
> Just noting that the "Signed in" information will not be visible with the new designs

I recall there being a bit of back and forth on whether that was something the team saw value in. It was purposefully omitted from the designs. We were not sure at the time of grooming so added the following AC to cover discussion on the topic: 
* It's been reviewed if there's usefulness in including a timestamp related to the current session data.

> I think its worth another conversation around whether its worth creating a new UI when this might be sufficient as an MVP.

In regards to an MVP, the scaffolding and UI is in a final stage of peer review and is pretty much done. So there's not really 'additional' effort in shipping this.

**Comment by brynwhyman** [comment]
I've also noted this in the issue on [2 Feb](https://github.com/silverstripe/silverstripe-session-manager/issues/12#issuecomment-771281383)

**Comment by clarkepaul** [comment]
I've just seen the UI in a live demo, I think we can follow the provided designs with some minor tweaks to allow the full date to show on hover if its an easy thing to do. If that is difficult then I think its fine to leave to leave the Signed in date out. I did this quick screen shot to show how it could be done but will update the design accordingly. I also mentioned BS tooltips are nicer than title text but see how we go.
![image](https://user-images.githubusercontent.com/555033/110561210-26c90b80-81ac-11eb-9f24-f928aee1439e.png)

**Comment by clarkepaul** [comment]
... and on the current view swap the order of "Current" and 'IP" so it matches the other sessions. Just going to add dates to design for signed in on the current session to see if it's good or not.
![image](https://user-images.githubusercontent.com/555033/110563549-5bd75d00-81b0-11eb-8e63-cea0cb91479f.png)

**Comment by clarkepaul** [comment]
Just posted an update of the [designs](https://projects.invisionapp.com/share/ANZZEC4XUTQ#/screens/439163639_CMS_-_Login_-_Session_Management_-_Remove_A_Device_-_List) @bergice, basically a catchup of designs already discussed hopefully. Some new stuff with the section label and logout action. 

For the section label, I've taken a look around to see what would make the most sense to people and think retaining "Device" should make sense. That seems to fit closer to the majority scenario of a different physical device. I think we should make it slightly clearer with the addition of "Authenticated devices" so that people have more context about it as login/session type information. In saying that, session/device both seem to work well, so happy to hear if there is any objection to this.

For the logout transition (although not part of this issue), this was designed without physically testing it out so keen to work with whoever implements it to adjust as needed if not quite right.
