### ISSUE TITLE
Reference 'sessions' not 'devices'

### ISSUE THREAD

**Issue by brynwhyman** [kinglozzer/silverstripe-session-manager#69]
## Overview
There is some expected overlap between the phrases 'sessions' and 'devices' when looking at this feature. We need to use both terms to paint a clear picture of what's happening. Upon reviewing the current UI, there has been some discussion on tweaking the use of these terms slightly.

At a high-level, it's suggested that we refer to the information and frame it as a 'session', not a 'device' That's also more technically correct given it's the session data that the module is tracking - there's no 'device_ID' for example.

* In the main component, we currently refer to the information as "Authenticated devices" - which makes less sense when it's possible to have multiple sessions against a single device, see:
https://invis.io/ANZZEC4XUTQ#/439163639_CMS_-_Login_-_Session_Management_-_Remove_A_Device_-_List

## Acceptance Criteria
- [ ]  The label in the Profile admin is updated
- [ ] Review existing docs and screenshots that may reference this UI, make necessary changes

## PRs
- [ ] https://github.com/silverstripe/silverstripe-session-manager/pull/71

## Notes
-

**Comment by brynwhyman** [comment]
cc @clarkepaul do you want to chime in with your thoughts on this one?

**Comment by brynwhyman** [comment]
This view from GitHub sparked the conversation:
![image](https://user-images.githubusercontent.com/15868440/116190375-a6bc2c80-a77e-11eb-92d6-c345969aaa30.png)

**Comment by michalkleiner** [comment]
If there's a note somewhere at the beginning of the docs about what each of the terms means and that a single device can hold several sessions, then I'd prefer going with sessions wherever possible and contextually correct.

**Comment by clarkepaul** [comment]
Referring to "Sessions" makes much more sense for the current functionality we currently have (I think the functionality is fine with a wording change). The easy call to make is changing the label of the section. Just having "Sessions" instead of "Authenticated devices" might be a little abrupt for our audience so playing with a few options, whatever it is I think it should be understandable if you are looking at someone else's sessions too (if devs have provided that extra functionality). 

1.  Active sessions
2.  Login sessions
3.  Device sessions
4.  User sessions
5.  Where you're logged in
6.  Sessions
7.  Logged in
 
I would have thought it was obvious as to what people should do if they don't recognise a session so I'm a little surprised GitHub explains the area, especially with the audience they have, but then again this is a fairly important section and maybe these types of patterns a more common now than they used to be. The likes of Facebook don't provide any additional info but their label is super easy to understand for non-tech types "Where you're logged in".

By simply not using the word "Device" it makes a lot more sense, even if the word "Sessions" wasn't used.
I think I quite like the simplicity of "Logged in", it makes sense to all user types, and also implies sessions.

**Comment by bergice** [comment]
> Referring to "Sessions" makes much more sense for the current functionality we currently have (I think the functionality is fine with a wording change). The easy call to make is changing the label of the section. Just having "Sessions" instead of "Authenticated devices" might be a little abrupt for our audience so playing with a few options, whatever it is I think it should be understandable if you are looking at someone else's sessions too (if devs have provided that extra functionality).
> 
> 1. Active sessions
> 2. Login sessions
> 3. Device sessions
> 4. User sessions
> 5. Where you're logged in
> 6. Sessions
> 7. Logged in
> 
> I would have thought it was obvious as to what people should do if they don't recognise a session so I'm a little surprised GitHub explains the area, especially with the audience they have, but then again this is a fairly important section and maybe these types of patterns a more common now than they used to be. The likes of Facebook don't provide any additional info but their label is super easy to understand for non-tech types "Where you're logged in".
> 
> By simply not using the word "Device" it makes a lot more sense, even if the word "Sessions" wasn't used.
> I think I quite like the simplicity of "Logged in", it makes sense to all user types, and also implies sessions.

@clarkepaul I've gone with "Login Sessions" as you've suggested it and it's literally the name of the class that stores the data which will keep developers happy as well.

**Comment by clarkepaul** [comment]
Cool, just make sure its lowercase 's' for Login **s**essions (sentence case)
